import type { Config } from 'tailwindcss'

export default <Partial<Config>>{
  darkMode: 'class',
  content: [
    './components/**/*.{js,vue,ts}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
    './plugins/**/*.{js,ts}',
    './app.vue',
  ],
  theme: {
    extend: {
      colors: {
        'surface-container-low': '#f3f3f5',
        'surface-tint': '#4c56af',
        'surface-container': '#eeeef0',
        'primary': '#000666',
        'on-error-container': '#93000a',
        'surface-container-highest': '#e2e2e4',
        'on-tertiary': '#ffffff',
        'primary-fixed': '#e0e0ff',
        'surface-container-high': '#e8e8ea',
        'inverse-on-surface': '#f0f0f2',
        'secondary-fixed-dim': '#78dc77',
        'outline': '#767683',
        'on-tertiary-container': '#b29089',
        'on-surface-variant': '#454652',
        'tertiary-fixed-dim': '#e3beb6',
        'primary-fixed-dim': '#bdc2ff',
        'surface-container-lowest': '#ffffff',
        'on-background': '#1a1c1d',
        'background': '#f9f9fb',
        'on-tertiary-fixed-variant': '#5b403b',
        'on-surface': '#1a1c1d',
        'on-secondary-container': '#00731e',
        'surface-dim': '#d9dadc',
        'tertiary-fixed': '#ffdad3',
        'on-error': '#ffffff',
        'secondary-fixed': '#94f990',
        'on-primary-fixed-variant': '#343d96',
        'inverse-primary': '#bdc2ff',
        'inverse-surface': '#2f3132',
        'on-tertiary-fixed': '#2b1612',
        'tertiary-container': '#422a25',
        'secondary-container': '#91f78e',
        'outline-variant': '#c6c5d4',
        'tertiary': '#2a1611',
        'surface-variant': '#e2e2e4',
        'on-secondary-fixed': '#002204',
        'on-primary-fixed': '#000767',
        'error-container': '#ffdad6',
        'surface': '#f9f9fb',
        'on-primary-container': '#8690ee',
        'on-secondary-fixed-variant': '#005313',
        'on-secondary': '#ffffff',
        'primary-container': '#1a237e',
        'on-primary': '#ffffff',
        'surface-bright': '#f9f9fb',
        'secondary': '#006e1c',
        'error': '#ba1a1a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '16px',
        'stack-md': '16px',
        'stack-sm': '8px',
        'stack-lg': '32px',
        'margin-desktop': '64px',
        'gutter': '24px',
        'base-unit': '8px',
      },
      fontFamily: {
        'headline-md-mobile': ['Public Sans', 'sans-serif'],
        'body-lg': ['Public Sans', 'sans-serif'],
        'headline-md': ['Public Sans', 'sans-serif'],
        'headline-sm': ['Public Sans', 'sans-serif'],
        'label-sm': ['Public Sans', 'sans-serif'],
        'display-lg': ['Public Sans', 'sans-serif'],
        'body-md': ['Public Sans', 'sans-serif'],
      },
      fontSize: {
        'headline-md-mobile': ['28px', { lineHeight: '34px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
